- name: "Gather facts from Arista switches"
  hosts: leafs
  gather_facts: no

  tasks:
    - name: Gather facts (eos)
      arista.eos.eos_facts:
  
    - name: Load vars file based on ansible_net_system
      ansible.builtin.include_vars: "vars/{{ ansible_net_system }}.yml"
    
    - name: Tell user we found an Arista switch
      debug:
        msg: "Arista switch detected"
      when: ansible_net_system == 'eos'
 
    - name: Collect show version information
      arista.eos.eos_command:
        commands: "show version"
      register: show_version
        
    - name: Ensure no strange CPU architectures are detected
      ansible.builtin.assert:
        that:
          - "show_version.stdout_lines | select('search', 'Architecture: s390') | list | count < 1"
        fail_msg: "Oh no"
        success_msg: "All is well"

    - name: Fail if SLA is not premium
      fail:
        msg: "Warning: SLA is {{ switch_sla }}"
      when: switch_sla != "premium"
