- name: "Backup leafs"
  hosts: leafs
  gather_facts: no
  tasks:
    - name: Backup cEOS switches
      arista.eos.eos_config:
        backup: yes
        backup_options:
          dir_path: /home/student/advanced-networking-workshop/backups
      become: yes
