- name: "Show interfaces on leafs"
  hosts: leafs
  gather_facts: no
  become: yes
  tasks:
    - name: Show summary of interface statuses
      arista.eos.eos_command:
        commands: "show interface status"
      register: sh_int_stat

    - name: Print collected interface information
      debug:
        msg: "{{ sh_int_stat.stdout_lines }}"
